### ISSUE TITLE
equipment provider

### ISSUE THREAD

**Issue by OmarAlghamdi** [OmarAlghamdi/walkly-android#31]
make the logic that choose equipment for the battle 

- get it user's equipment from the database (it should work while offline)
- provide an interface to the battle activity to get equipment's info
- equipment should be the right for the battle type

Future:
- make sure you implementation can be used to in online battles also and provide the right equipment

**Comment by A7madHD** [comment]
Since choosing the equipment is only for online, should i implement something else and leave this for the next 30%?
